// Code generated by Kitex v0.14.1. DO NOT EDIT.

package cryptopriceservice

import (
	"context"
	cryptov1 "crypto-info/kitex_gen/crypto/v1"
	v1 "crypto-info/kitex_gen/crypto/v1"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetPrice": kitex.NewMethodInfo(
		getPriceHandler,
		newGetPriceArgs,
		newGetPriceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetBTCPrice": kitex.NewMethodInfo(
		getBTCPriceHandler,
		newGetBTCPriceArgs,
		newGetBTCPriceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	cryptoPriceServiceServiceInfo                = NewServiceInfo()
	cryptoPriceServiceServiceInfoForClient       = NewServiceInfoForClient()
	cryptoPriceServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return cryptoPriceServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return cryptoPriceServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return cryptoPriceServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CryptoPriceService"
	handlerType := (*cryptov1.CryptoPriceService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "crypto.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.14.1",
		Extra:           extra,
	}
	return svcInfo
}

func getPriceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetPriceRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(cryptov1.CryptoPriceService).GetPrice(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetPriceArgs:
		success, err := handler.(cryptov1.CryptoPriceService).GetPrice(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetPriceResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetPriceArgs() interface{} {
	return &GetPriceArgs{}
}

func newGetPriceResult() interface{} {
	return &GetPriceResult{}
}

type GetPriceArgs struct {
	Req *v1.GetPriceRequest
}

func (p *GetPriceArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetPriceArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetPriceRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetPriceArgs_Req_DEFAULT *v1.GetPriceRequest

func (p *GetPriceArgs) GetReq() *v1.GetPriceRequest {
	if !p.IsSetReq() {
		return GetPriceArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetPriceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetPriceArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetPriceResult struct {
	Success *v1.GetPriceResponse
}

var GetPriceResult_Success_DEFAULT *v1.GetPriceResponse

func (p *GetPriceResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetPriceResult) Unmarshal(in []byte) error {
	msg := new(v1.GetPriceResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetPriceResult) GetSuccess() *v1.GetPriceResponse {
	if !p.IsSetSuccess() {
		return GetPriceResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetPriceResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetPriceResponse)
}

func (p *GetPriceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetPriceResult) GetResult() interface{} {
	return p.Success
}

func getBTCPriceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetBTCPriceRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(cryptov1.CryptoPriceService).GetBTCPrice(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetBTCPriceArgs:
		success, err := handler.(cryptov1.CryptoPriceService).GetBTCPrice(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetBTCPriceResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetBTCPriceArgs() interface{} {
	return &GetBTCPriceArgs{}
}

func newGetBTCPriceResult() interface{} {
	return &GetBTCPriceResult{}
}

type GetBTCPriceArgs struct {
	Req *v1.GetBTCPriceRequest
}

func (p *GetBTCPriceArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetBTCPriceArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetBTCPriceRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetBTCPriceArgs_Req_DEFAULT *v1.GetBTCPriceRequest

func (p *GetBTCPriceArgs) GetReq() *v1.GetBTCPriceRequest {
	if !p.IsSetReq() {
		return GetBTCPriceArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetBTCPriceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetBTCPriceArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetBTCPriceResult struct {
	Success *v1.GetPriceResponse
}

var GetBTCPriceResult_Success_DEFAULT *v1.GetPriceResponse

func (p *GetBTCPriceResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetBTCPriceResult) Unmarshal(in []byte) error {
	msg := new(v1.GetPriceResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetBTCPriceResult) GetSuccess() *v1.GetPriceResponse {
	if !p.IsSetSuccess() {
		return GetBTCPriceResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetBTCPriceResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetPriceResponse)
}

func (p *GetBTCPriceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetBTCPriceResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetPrice(ctx context.Context, Req *v1.GetPriceRequest) (r *v1.GetPriceResponse, err error) {
	var _args GetPriceArgs
	_args.Req = Req
	var _result GetPriceResult
	if err = p.c.Call(ctx, "GetPrice", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetBTCPrice(ctx context.Context, Req *v1.GetBTCPriceRequest) (r *v1.GetPriceResponse, err error) {
	var _args GetBTCPriceArgs
	_args.Req = Req
	var _result GetBTCPriceResult
	if err = p.c.Call(ctx, "GetBTCPrice", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
