# 应用配置
app:
  name: "crypto-info"
  version: "v1.0.0"
  env: "development" # development, staging, production
  debug: true
  timezone: "Asia/Shanghai"

# 服务器配置
server:
  http:
    host: "0.0.0.0"
    port: 8080
    read_timeout: 30s
    write_timeout: 30s
    idle_timeout: 60s
    max_header_bytes: 1048576 # 1MB
  grpc:
    host: "0.0.0.0"
    port: 9090
    timeout: 30s

# 日志配置
log:
  level: "info" # debug, info, warn, error
  format: "json" # json, text
  output: "stdout" # stdout, stderr, file
  file_path: "logs/app.log"
  max_size: 100 # MB
  max_age: 30 # days
  max_backups: 10
  compress: true

# 数据库配置
database:
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    pool_size: 10
    min_idle_conns: 5
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout: 3s
    pool_timeout: 4s
    idle_timeout: 300s
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "password"
    database: "crypto_info"
    charset: "utf8mb4"
    parse_time: true
    loc: "Local"
    max_open_conns: 100
    max_idle_conns: 10
    conn_max_lifetime: 3600s

# 外部API配置
external_api:
  huobi:
    base_url: "https://api.huobi.pro"
    timeout: 10s
    retry_times: 3
    retry_interval: 1s
  binance:
    base_url: "https://api.binance.com"
    timeout: 10s
    retry_times: 3
    retry_interval: 1s

# 缓存配置
cache:
  price_ttl: 300s # 5分钟
  volume_ttl: 300s # 5分钟
  default_ttl: 600s # 10分钟

# 监控配置
monitoring:
  metrics:
    enabled: true
    path: "/metrics"
    port: 9091
  tracing:
    enabled: true
    jaeger_endpoint: "http://localhost:14268/api/traces"
    service_name: "crypto-info"
    sample_rate: 0.1
  health_check:
    enabled: true
    path: "/health"
    interval: 30s

# 限流配置
rate_limit:
  enabled: true
  requests_per_second: 100
  burst: 200
  cleanup_interval: 60s

# 安全配置
security:
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["Content-Type", "Authorization", "X-Request-ID"]
    allow_credentials: true
    max_age: 86400
  jwt:
    secret: "your-jwt-secret-key"
    expire_time: 24h
    issuer: "crypto-info"
  session:
    enabled: true
    cookie_name: "crypto_session"
    secret: "your-session-secret-key-32-chars"
    max_age: 24h
    secure: false
    http_only: true
    same_site: "lax"
    domain: ""
    path: "/"
    store: "redis"

# 业务配置
business:
  supported_symbols: ["BTC", "ETH", "LTC", "BCH", "ADA", "DOT", "LINK", "XRP"]
  default_symbol: "BTC"
  max_analysis_days: 365
  default_analysis_days: 10
  mock_data_enabled: true

# RocketMQ 消息队列配置
rocketmq:
  enabled: false
  name_servers: ["localhost:9876"]
  producer:
    group_name: "crypto_info_producer"
    retry_times: 3
    send_msg_timeout: 3s
    compress_level: 4
  consumer:
    group_name: "crypto_info_consumer"
    consume_from_where: "CONSUME_FROM_LAST_OFFSET"
    consume_message_batch: 1
    pull_interval: 1s
    pull_batch_size: 32