// Code generated by Kitex v0.14.1. DO NOT EDIT.

package cryptovolumeservice

import (
	"context"
	v1 "crypto-info/kitex_gen/crypto/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetVolumeAnalysis(ctx context.Context, Req *v1.GetVolumeAnalysisRequest, callOptions ...callopt.Option) (r *v1.GetVolumeAnalysisResponse, err error)
	GetMarketVolumeFluctuation(ctx context.Context, Req *v1.GetMarketVolumeFluctuationRequest, callOptions ...callopt.Option) (r *v1.GetMarketVolumeFluctuationResponse, err error)
	GetVolumeComparison(ctx context.Context, Req *v1.GetVolumeComparisonRequest, callOptions ...callopt.Option) (r *v1.GetVolumeComparisonResponse, err error)
	GetTopVolumeCoins(ctx context.Context, Req *v1.GetTopVolumeCoinsRequest, callOptions ...callopt.Option) (r *v1.GetTopVolumeCoinsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCryptoVolumeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCryptoVolumeServiceClient struct {
	*kClient
}

func (p *kCryptoVolumeServiceClient) GetVolumeAnalysis(ctx context.Context, Req *v1.GetVolumeAnalysisRequest, callOptions ...callopt.Option) (r *v1.GetVolumeAnalysisResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVolumeAnalysis(ctx, Req)
}

func (p *kCryptoVolumeServiceClient) GetMarketVolumeFluctuation(ctx context.Context, Req *v1.GetMarketVolumeFluctuationRequest, callOptions ...callopt.Option) (r *v1.GetMarketVolumeFluctuationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMarketVolumeFluctuation(ctx, Req)
}

func (p *kCryptoVolumeServiceClient) GetVolumeComparison(ctx context.Context, Req *v1.GetVolumeComparisonRequest, callOptions ...callopt.Option) (r *v1.GetVolumeComparisonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVolumeComparison(ctx, Req)
}

func (p *kCryptoVolumeServiceClient) GetTopVolumeCoins(ctx context.Context, Req *v1.GetTopVolumeCoinsRequest, callOptions ...callopt.Option) (r *v1.GetTopVolumeCoinsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTopVolumeCoins(ctx, Req)
}
